#!/bin/bash

echo "Digite o endereço IP que deseja aplicar:"
read endereco_ip

if [[ ! $endereco_ip =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    echo "IP inválido. Por favor, insira um endereço IP válido."
    exit 1
fi

echo "Digite a máscara de rede que deseja aplicar:"
read mascara_rede

if [[ ! $mascara_rede =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
    echo "IP inválido. Por favor, insira um endereço IP válido."
    exit 1
fi

configurar_rede() {
    endereco_ip=$1
    mascara_rede=$2
    nome_host=SECNTL-6ZDD703

    resultado=$(sudo ifconfig wlo1 $endereco_ip netmask $mascara_rede up)
    resultado_hostname=$(sudo hostnamectl set-hostname $nome_host)

    if [ $? -eq 0 ]; then
    	echo "
Sucesso! A rede foi configurada com sucesso.
Endereço IP: $endereco_ip
Máscara de Rede: $mascara_rede"
    else
        echo "Falha: não foi possível configurar a rede."
    fi
}

configurar_rede $endereco_ip $mascara_rede $nome_host

