#!/bin/bash

echo "Digite o endereço IP no qual deseja fazer uma varredura das portas:"
read endereco

varredura_portas() {
        endereco=$1

        resultado=$(nmap $endereco)
	echo "$resultado"

        if [ $? -eq 0 ] ;
        then
                echo "Varredura das portas do endereço $endereco foi realizada com sucesso!" 
        else 
                echo "Falha: não foi possível fazer a verificação ds portas do endereço $endereco." 
        fi
}

varredura_portas $endereco

